# docker-compose.prod.yml
version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: prod-neuro-note-backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: prod-neuro-note-frontend
    ports:
      - "80:80"

  postgres:
    image: postgres:15
    container_name: prod-neuro-postgres
    environment:
      POSTGRES_USER: neuro
      POSTGRES_PASSWORD: neuro
      POSTGRES_DB: neuronote
    ports:
      - "5432:5432"
    volumes:
      - prod-postgres-data:/var/lib/postgresql/data
      - ./backend/db-init:/docker-entrypoint-initdb.d

volumes:
  prod-postgres-data:
