# docker-compose.dev.yml
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: dev-neuro-note-backend
    command: npm run start:dev
    env_file: ./backend/.env_dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: dev-neuro-note-frontend
    command: npx ng serve --host 0.0.0.0 --port 4200 --poll 2000
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: dev-neuro-note-postgres
    environment:
      POSTGRES_USER: neuro
      POSTGRES_PASSWORD: neuro
      POSTGRES_DB: neuronote
    ports:
      - "5433:5432"
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
      - ./backend/db-init:/docker-entrypoint-initdb.d
      
volumes:
  dev-postgres-data: